version: '3.7'

services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./server/:/server/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    env_file: .env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_DB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
    mongodb_data: